name: Build YAFU
on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build YAFU in Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          labels: |
            org.opencontainers.image.source=https://github.com/nomeaning777/yafu-build
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ github.actor }}/yafu:latest
          push: true
